"""Fix tenant_id datatype mismatch

Revision ID: a79d78e4183f
Revises: 1f6d85a788b7
Create Date: 2025-02-23 05:25:14.134703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a79d78e4183f'
down_revision: Union[str, None] = '1f6d85a788b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
